# ~/.config/starship.toml
add_newline = true
# Increase the default command timeout to 2 seconds
command_timeout = 2000

format = """\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$time\
$python
$shell\
$character"""

# Disable the line break between the first and second prompt lines
[line_break]
disabled = false

[time]
format = '[\[$time\]]($style) '
time_format = '%y/%m/%d %H:%M:%S'
disabled = false

[shell]
fish_indicator = ' ğŸŸ'
bash_indicator = ' ğŸš'
unknown_indicator = 'mystery shell'
style = 'cyan bold'
disabled = false

